export const SAVED_EDITED_TASK = 'SAVED_EDITED_TASK';
export const EDIT_TASK_PROPERTY = 'EDIT_TASK_PROPERTY';
export const EDIT_USER_PROPERTY = 'EDIT_USER_PROPERTY';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const TASK_DETAILS = 'TASK_DETAILS';
export const INVALID_USER = 'INVALID_USER';
export const SET_USER = 'SET_USER';
export const USER_REGISTERED = 'USER_REGISTERED';
